### ISSUE TITLE
Tweaks need to be made to the UI.

### ISSUE THREAD

**Issue by Goy288** [kperdue2002/AdvDotNetTeamSrcCntrl#10]
As of now, I don't believe the current UI is designed all that well. It looks as if all the tasks for it need to be on one page, which is something that I don't think works.

The assignment says that the program needs to have CRUD functionality.
**C**reate: A window for manually adding orders.
**R**ead: A window that allows the program to view the orders page by page.
**U**pdate: A window that allows editing of preexisting orders.
**D**elete: A button, preferably either on the read or update page, that allows the deletion of an order.

Opening window mockup, I'll show off a few more ideas once I get home:
![image](https://user-images.githubusercontent.com/44177200/73990801-1c7c7400-48ff-11ea-8715-8139e4f716da.png)

**Comment by Goy288** [comment]
Alright, so when you press Add, it takes you to a simple form you must fill out. Make sure all the values that lie in the Order class are filled out. Leave PhoneNumber as optional, and don't manually insert anything for OrderID.

The View Orders button takes you to a table, displaying the orders page by page. Make sure there's a button that allows you to edit the selected order entry. The same with the delete button.

Of course, feel free to take any liberties with my suggestions, but make sure that the program fully implements CRUD functionality.

**Comment by kperdue2002** [comment]
im more a "on one page" kind of person, but I could see what youre getting at. I'll make the changes, I am a programmer and not a designer afterall

**Comment by Goy288** [comment]
Alrighty then. 

Also one last recommendation that I think could help, is to recycle the Add UI for when editing an entry, by making it so the Add form accepts a boolean at the start that determines whether or not it's editing or adding an Order object.
