### ISSUE TITLE
Create and implement an add form.

### ISSUE THREAD

**Issue by Goy288** [kperdue2002/AdvDotNetTeamSrcCntrl#11]
As explained in #10, the program requires an add form that has a simple form you must fill out. Make sure all the values that lie in the Order class are filled out. Leave PhoneNumber as optional, and don't manually insert anything for OrderID.

**Comment by kperdue2002** [comment]
my form was merged, and all the buttons/fields were hooked up. in redoing that form did you get rid of all the functionality?

**Comment by Goy288** [comment]
It's still in the CRUD-Functionality branch right now, but the Add form is now functional(took me a while to learn I was using the wrong EntityFramework). I'm just currently working on the view form right now.
![image](https://user-images.githubusercontent.com/44177200/74877756-d2da5300-531a-11ea-9dbe-9ee4dcd1cbc3.png)

**Comment by kperdue2002** [comment]
okay. when you finish the form I can handle the delete functionality in issue #14

**Comment by Goy288** [comment]
Got it
